// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5qKv6UUTfilrT6f-7gLKiT4oezOGsdg',
    appId: '1:744849529317:web:dcf094391be7b5f759b70c',
    messagingSenderId: '744849529317',
    projectId: 'note-app-f0070',
    authDomain: 'note-app-f0070.firebaseapp.com',
    storageBucket: 'note-app-f0070.appspot.com',
    measurementId: 'G-SQLJ9WWSP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zeWsY7X0DpO8yc9V9PBc3jJdKRe-2_Y',
    appId: '1:744849529317:android:33f36bc4d42a1fce59b70c',
    messagingSenderId: '744849529317',
    projectId: 'note-app-f0070',
    storageBucket: 'note-app-f0070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxWKqj8xaLJBcOdHajiwDVKkLOYDxcbds',
    appId: '1:744849529317:ios:1de24b20fa1c7f3359b70c',
    messagingSenderId: '744849529317',
    projectId: 'note-app-f0070',
    storageBucket: 'note-app-f0070.appspot.com',
    iosBundleId: 'com.example.notesAppCompleteProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxWKqj8xaLJBcOdHajiwDVKkLOYDxcbds',
    appId: '1:744849529317:ios:1de24b20fa1c7f3359b70c',
    messagingSenderId: '744849529317',
    projectId: 'note-app-f0070',
    storageBucket: 'note-app-f0070.appspot.com',
    iosBundleId: 'com.example.notesAppCompleteProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5qKv6UUTfilrT6f-7gLKiT4oezOGsdg',
    appId: '1:744849529317:web:05cfbb64caf5176859b70c',
    messagingSenderId: '744849529317',
    projectId: 'note-app-f0070',
    authDomain: 'note-app-f0070.firebaseapp.com',
    storageBucket: 'note-app-f0070.appspot.com',
    measurementId: 'G-YSY506YHLS',
  );
}
